[mgr]
ratio = [0, 4, 4]
sort_by = "natural"
sort_sensitive = true
sort_dir_first = true

# For lack of better handling of swedish.
sort_translit = true
linemode = "none"
show_hidden = true
show_symlink = true

title_format = "{cwd}"

[preview]
wrap = "no"
tab_size = 4
